from prompts.chat import STRICT_GROUNDED_SYSTEM_PROMPT
from prompts.flashcards import ADVANCED_ANKI_FLASHCARDS_PROMPT, DEFAULT_FLASHCARDS_PROMPT, FLASHCARDS_PROMPTS
from prompts.lesson import LESSON_MARKDOWN_SYSTEM_PROMPT, LESSON_PODCAST_SYSTEM_PROMPT
from prompts.medulingo import MEDULINGO_PODCAST_PROMPT
from prompts.notes import DEFAULT_NOTES_PROMPT
from prompts.podcast import DEFAULT_PODCAST_PROMPT
from prompts.test import DEFAULT_TEST_PROMPT_SYSTEM

__all__ = [
    "STRICT_GROUNDED_SYSTEM_PROMPT",
    "DEFAULT_PODCAST_PROMPT",
    "DEFAULT_NOTES_PROMPT",
    "DEFAULT_FLASHCARDS_PROMPT",
    "ADVANCED_ANKI_FLASHCARDS_PROMPT",
    "FLASHCARDS_PROMPTS",
    "DEFAULT_TEST_PROMPT_SYSTEM",
    "LESSON_MARKDOWN_SYSTEM_PROMPT",
    "LESSON_PODCAST_SYSTEM_PROMPT",
    "MEDULINGO_PODCAST_PROMPT",
]
